version: '3.7'

services:
  tomcat:
    image: tomcat:jre8-openjdk-bullseye
    volumes:
      - ./tomcat/:/usr/local/tomcat
    ports:
      - 8080:8080
    networks:
      - tp_backend

networks:
  tp_backend:
    external: true
